### ISSUE TITLE
javascript input is not printed on console.

### ISSUE THREAD

**Issue by vivek80801** [adarshaacharya/CodeTreats#13]
**Describe the bug**
javascript input is not printed on console.

**To Reproduce**
1. Go to **CodeTreats**
2. write this code
```javascript

const readline = require("readline");
const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

rl.question("What is your name ? ", function(name) {
    rl.question("Where do you live ? ", function(country) {
        console.log(`${name}, is a citizen of ${country}`);
        rl.close();
    });
});

rl.on("close", function() {
    console.log("\nBYE BYE !!!");
    process.exit(0);
});

```

3. select the javascript as language

**Expected behavior**
It should take input and print it on console. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04
 - Browser :chrome

**Additional context**
This code works perfectly in my terminal.

**Comment by adarshaacharya** [comment]
The way **CodeTreats** works is that it takes the input (stdin) at the time of executing the code. Any input entered between the running of program isn't accepted. For the above feature, I've to make output terminal writable too.. Since all the code execution of app depends on [glot](https://glot.io/) so let's see if this feature is support by it or not. 


THank you for raising issue. I will definitely look into it.
